# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: $(Build.Major).$(Build.Minor).$(BuildId)
trigger:
- master

variables:
  Build.Major: 1
  Build.Minor: 0
  Build.Patch: $(Build.BuildId)
  Build.Configuration: 'Release'
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops
  IQSharp.Hosting.Env: 'build-agent-katas'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: scripts/steps.yml
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: scripts/steps.yml
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: scripts/steps.yml

